/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Calculator {

    public int Calculate(int a, int b, String operator) {
        int result=0;
        switch (operator)
        {
            case "+": result=a+b;
                break;
            case "-": result=a-b;
                break;
            case "*": result=a*b;
                break;
            case "/": result=a/b;
                break;
        }
        return result;
    }

    public static void main(String[] args) {
        InputHandler input = new InputHandler();
        Calculator calc = new Calculator();
        System.out.println(calc.Calculate(input.getOperand1(), input.getOperand2(), input.getOperator()));
    }
}
