/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;

import java.io.ByteArrayInputStream;
import java.util.Objects;
import java.util.Scanner;

import static org.testng.Assert.*;

public class CalculatorTest {


    @DataProvider(name="input")
    public Object[][] input(){
        return new Object[][]{
                {0, 0, "*", 0},
                {0, 0, "+", 0 },
                {0, 0, "-", 0},
                {2, 3, "+", 5},
                {2, 10, "+", 12},
                {122, 23, "-", 99},
                {4, 3, "-", 1},
                {4, 4, "/", 1},
                {100, 1, "/", 100},
                {2, 3, "*", 6},
                {6, 3, "/", 2},
        };
    }

    @Test(dataProvider = "input")
    public void CheckCalculations( int a, int b, String operator, int expected) {
        Calculator classUnderTest = new Calculator();
        assertEquals(classUnderTest.Calculate(a,b,operator), expected, "Counts properly");
    }


    @Test
    public void IntegrationTest() {
        Calculator classUnderTest = new Calculator();
        InputHandler input = new InputHandler(150,51,"-");
        assertEquals(classUnderTest.Calculate(input.getOperand1(),input.getOperand2(),input.getOperator()), 99, "Counts properly");
    }
}
